AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-serverless-retrazo-de-vuelos-scl


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  ProbaRetrazoVolSCLFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: lambda.handler.app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        ProbaRetrazoVolSCL:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /prob_delay
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProbaRetrazoVolSCLApi:
    Description: "API Gateway endpoint URL for Prod stage for prop delay function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/prob_delay/"
  ProbaRetrazoVolSCLFunction:
    Description: "Proba func Lambda Function ARN"
    Value: !GetAtt ProbaRetrazoVolSCLFunction.Arn
  ProbaRetrazoVolSCLFunctionIamRole:
    Description: "Implicit IAM Role created for ProbaRetrazoVolSCL function"
    Value: !GetAtt ProbaRetrazoVolSCLFunctionRole.Arn
