AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-serverless-retrazo-de-vuelos-scl

Globals:
  Function:
    Timeout: 30
    MemorySize: 512  # Ajusta la memoria según las necesidades de tu función

Resources:
  ProbaRetrazoVolSCLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_handler/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref MyApiKey

      Events:
        ProbaRetrazoVolSCL:
          Type: Api
          Properties:
            Path: /prob_delay
            Method: get

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      ApiKeyRequired: true

  MyApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: MyApiKey
      Description: Mi API Key
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Description: Usage plan for the API Key
      Quota:
        Limit: 100000  # Ajusta el límite según tus necesidades
        Period: MONTH
      Throttle:
        BurstLimit: 100  # Ajusta según tus necesidades
        RateLimit: 50  # Ajusta según tus necesidades

Outputs:
  ProbaRetrazoVolSCLApi:
    Description: "API Gateway endpoint URL for Prod stage for prop delay function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ProbaRetrazoVolSCLFunction:
    Description: "Proba func Lambda Function ARN"
    Value: !GetAtt ProbaRetrazoVolSCLFunction.Arn
