on:
  push:
    branches:
      - master
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1
        with:
          aws-sam-cli-version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # sam build
      - name: Build SAM application
        run: sam build --use-container

      # Run Unit tests- Specify unit tests here

      # sam deploy
      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name api-serverless-retrazo-de-vuelos-scl --s3-bucket api-serverless-retrazo-de-vuelos-scl --capabilities CAPABILITY_IAM --region us-east-1


